Digital medlemsrapportering
ix-sthlm/ix-sthlm.github.io pull request #2
Opened 2019-03-31 17:43 UTC by etu

Då den första integritetspolicyn och nuvarande medlemsrapporteringssystem är instiftat av styrelsen på ett arbetsmöte så kan vi på samma nivå ändra denna policy.

Jag har skapat ett utkast på formulär som finns länkat i ändringen av medlemssidan men här är länken igen:
https://docs.google.com/forms/d/e/1FAIpQLSdyz--d1xRFH5t9o-JwNerxnBQX7Oo3zNubyL1evJfK5J_9OQ/viewform

Ni får gärna reviewa både formuläret och ändrigarna av allt annat i denna PR.

Vi kan även prata om det på UFS imorgon.

Detta är för att minska tröskeln för nya medlemmar och slippa tolka vad folk skrivit på papper :stuck_out_tongue:

2019-03-31 20:40 UTC, MichaelStahre approved these changes

2019-03-31 21:16 UTC, Kira9204 approved these changes

2019-04-01 18:41 UTC, talyz requested changes
Bra initiativ! Lite formuleringar / stavningar bara...

2019-04-01 18:41 UTC, talyz commented on content/about_privacy.md
> +Denna information får du själv fylla i ett formulär som ägs av Distriktets
Borde nog vara "fylla i i ett formulär"

2019-04-01 18:41 UTC, talyz commented on content/about_privacy.md
> +Vi lagrar dina uppgifter i ett Google formulär på Distriktet's Google Drive.
"Google-formulär på Distriktets Google Drive"

2019-04-01 18:41 UTC, talyz commented on content/about_privacy.md
> +För att få ett utdrag eller att rätta dina uppgifter kan du kontakta oss i
"För att få ett utdrag på, eller korrigera, dina uppgifter"

2019-04-01 18:41 UTC, talyz commented on content/about_privacy.md
> +Den här policyn godkänner du när du fyller i vårat medlemsformulär för att
"vårt medlemsformulär"

2019-04-01 18:41 UTC, talyz commented on content/about_privacy.md
> +ansöka om medlemskap. Den kommer då uppdateras inför ett nytt år, så den
"Den uppdateras löpande och medlemmar meddelas om förändringar via e-post."

2019-04-08 17:37 UTC, talyz approved these changes

2019-04-09 15:03 UTC, DOSn3rd approved these changes
Ser finemang ut :)

2019-04-15 16:36 UTC, merged